### ISSUE TITLE
Check Optional date management

### ISSUE THREAD

**Issue by richiMarchi** [Mastercypher/Datdog#6]
found and completed date respectively in report and vaccination could be null, so it's crucial to check the management of that value on both sides

**Comment by richiMarchi** [comment]
generally speaking, it concerns every db field that can be null. Check it to make it work.

**Comment by AleRiccardi** [comment]
But if you push to the database in the moment of the creation a simple string like that ("") then you can avoid to check the moment of the download in the data if the specific value is null or not, you need only to do -> something != "".
